name: flood_depths
channels:
  - defaults
dependencies:
  - python>=3.7.7
  - pandas>=1.0.3
  - numpy>=1.18.1
  - scikit-learn>=0.22.1
  - matplotlib>=3.1.3
  - pip>=20.0.2
  - seaborn>=0.10.1
  - pillow=6.1.0
  - jupyter>=1.0.0
  - pip:
    - keras>=2.3.1
    - tensorflow>=2.2.0
